version: '3.8'
services:
  postgres:
    container_name: book-service-psql-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book-service-db
    ports:
      - "5432:5432"
  redis:
    container_name: book-service-redis-db
    image: redis:7.0.12
    ports:
      - "6379:6379"